{
 "title": "Predicted TOU Rate (INR)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Live Grid Power Cost Alert (INR)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "--#High Grid Power Cost Alert \r\nSELECT \r\n    instantaneous_actual_cost_inr,\r\n    Time\r\nFROM \r\n    solar_data9\r\nORDER BY \r\n    Time DESC  -- Sort by newest first\r\nLIMIT 1;"
    }
   ]
  },
  {
   "title": "High Predicted Tariff Rate Alerts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    predicted_tou_rates_inr,\r\n    Time\r\nFROM \r\n    solar_data9\r\nWHERE\r\n    Time < NOW()  -- Ensure that only records with Time before the current time are considered\r\nORDER BY \r\n    Time DESC  -- Sort by newest first\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "Energy Sold Back to Grid",
   "type": "stat",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    battery_level_kwh AS \"Battery Level (%)\",\r\n    tou_rates_inr AS \"TOU Rates (INR)\",\r\n    Time AS \"Timestamp\",\r\n    CASE \r\n        WHEN battery_level_kwh = 100 AND instantaneous_solar_generation_kwh > 0 \r\n        THEN instantaneous_solar_generation_kwh  -- Energy sold to grid\r\n        ELSE 0  -- No energy sold\r\n    END AS \"Energy Sold to Grid (kWh)\",\r\n    CASE \r\n        WHEN battery_level_kwh = 100 AND instantaneous_solar_generation_kwh > 0 \r\n        THEN instantaneous_solar_generation_kwh * tou_rates_inr  -- Calculate revenue\r\n        ELSE 0  -- No revenue if no energy sold\r\n    END AS \"Revenue from Grid (INR)\"\r\nFROM \r\n    solar_data9\r\nWHERE \r\n    Time = (SELECT MAX(Time) FROM solar_data9 WHERE Time <= CURRENT_TIMESTAMP)  -- Current time or last available time\r\nORDER BY \r\n    Time DESC  -- Sort by newest first\r\nLIMIT 1;\r\n"
    }
   ]
  },
  {
   "title": "High Predicted Tariff Rate Alerts",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyINR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  \r\n    predicted_tou_rates_inr,\r\n    Time\r\nFROM \r\n    solar_data9\r\nWHERE\r\n    Time < NOW()  -- Ensure that only records with Time before the current time are considered\r\nORDER BY \r\n    Time DESC  -- Sort by newest first\r\nLIMIT 1;\r\n"
    }
   ]
  }
 ]
}